name: Build and Publish

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Exit if not on main branch
        # head_ref for PR, ref_name for anything else
        if: endsWith(github.ref_name, 'main') == false
        run: exit -1
      # Setup .npmrc file
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r uwwave_chrome.zip dist
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r uwwave_lib.zip dist_lib
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.md;*.zip;"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: false
          tags: true
          verbose: true
      - run: yarn publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
